language: go
go:
- 1.13.x
cache:
  directories:
  - "$GOPATH/pkg/mod"
stages:
- test
jobs:
  include:
  - stage: test
    script:
    - go test ./... -coverprofile=coverage.out -covermode=atomic
      -p=1
    after_success:
    - bash <(curl -s https://codecov.io/bash)
